project:
  type: website
  output-dir: docs


website:
  title: "Mikael Hiberg Naghizadeh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: ongoing.qmd
        text: Ongoing Projects
    right:
      - icon: envelope
        href: "mailto:mikaelhnaghizadeh@gmail.com"
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/mhnagh.bsky.social

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    link-external-icon: true

editor: visual

